[package]
name = "reverse-proxy-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "0.2.8"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
